/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTActualTypes.ActualPilotWitness

/-!
# Generating the public theta-pilot region from actual outputs

Instead of accepting an unrelated `RHSData.thetaPilot`, this module defines it as the
union of a nonempty type of concrete outputs.  Membership of the native branch is then
definitional.  A common finite-support hypothesis is required because an arbitrary
infinite union of restricted-product regions need not be admissible.
-/

set_option linter.unusedVariables false
set_option linter.checkUnivs false

namespace IUTActualTypes

open Iut NumberField

universe u v w

variable {AG : AnabelianGeometry.{u}} {TG : TemperedGeometry AG}

/-- Actual-output data over one public large-volume container. -/
structure GeneratedOutputData
    {D : InitialThetaData AG TG}
    (C : LargeVolumeContainerData.{0, u, v} ℕ
      (Place ↥D.prime.torsionField)) : Type (max u (v + 1) (w + 1)) where
  Output : Type w
  outputNonempty : Nonempty Output
  realize : Output → ∀ i, C.AdmissibleRegion i
  /-- One finite support per capsule, uniform over every allowed output. -/
  support : ∀ i, Finset RationalPlace
  realize_eq_integral_outside :
    ∀ o i vQ, vQ ∉ support i →
      (realize o i).region vQ = (C.packet i vQ).integralRegion
  realize_le_logShell :
    ∀ o i, realize o i ≤ C.logShellAdmissible i

namespace GeneratedOutputData

variable {D : InitialThetaData AG TG}
variable {C : LargeVolumeContainerData.{0, u, v} ℕ
  (Place ↥D.prime.torsionField)}

/-- Capsule-wise union of all actual outputs. -/
noncomputable def unionRegion
    (G : GeneratedOutputData.{u, v, w} C)
    (i : Fin C.proc.length) : C.AdmissibleRegion i where
  region vQ := ⋃ o : G.Output, (G.realize o i).region vQ
  finiteSupport := by
    classical
    refine (G.support i).finite_toSet.subset ?_
    intro vQ hv
    simp only [Set.mem_setOf_eq] at hv
    by_contra houtside
    apply hv
    ext x
    constructor
    · intro hx
      rcases Set.mem_iUnion.mp hx with ⟨o, hx⟩
      have h := G.realize_eq_integral_outside o i vQ (by simpa using houtside)
      rw [h] at hx
      exact hx
    · intro hx
      let o : G.Output := Classical.choice G.outputNonempty
      apply Set.mem_iUnion.mpr
      refine ⟨o, ?_⟩
      have h := G.realize_eq_integral_outside o i vQ (by simpa using houtside)
      rw [h]
      exact hx

/-- Every actual output is contained in the generated union. -/
theorem realize_le_unionRegion
    (G : GeneratedOutputData.{u, v, w} C)
    (o : G.Output) (i : Fin C.proc.length) :
    G.realize o i ≤ G.unionRegion i := by
  intro vQ x hx
  exact Set.mem_iUnion.mpr ⟨o, hx⟩

/-- Log-shell containment is stable under the generated union. -/
theorem unionRegion_le_logShell
    (G : GeneratedOutputData.{u, v, w} C)
    (i : Fin C.proc.length) :
    G.unionRegion i ≤ C.logShellAdmissible i := by
  intro vQ x hx
  rcases Set.mem_iUnion.mp hx with ⟨o, hx⟩
  exact G.realize_le_logShell o i vQ hx

end GeneratedOutputData

/-- Complete public RHS constructor whose theta-pilot region is generated by actual
outputs rather than supplied independently. -/
structure GeneratedRHSData
    (D : InitialThetaData AG TG) : Type (max (u + 1) (v + 1) (w + 1)) where
  container : LargeVolumeContainerData.{0, u, v} ℕ
    (Place ↥D.prime.torsionField)
  proc_standard :
    container.proc = Procession.standard ((D.ℓ - 1) / 2)
  toRational_finite : ∀ x : FinitePlace ↥D.prime.torsionField,
    (container.toRational (Place.finite x)).residueChar = residueChar x
  toRational_infinite : ∀ x : InfinitePlace ↥D.prime.torsionField,
    container.toRational (Place.infinite x) = RationalPlace.infinite
  vol : LogVolumeData container
  hull : ContainerHullSystem container
  outputs : GeneratedOutputData.{u, v, w} container
  union_hullAdmissible :
    ∀ i, hull.IsAdmissible (outputs.unionRegion i)

namespace GeneratedRHSData

/-- Construct the actual public `RHSData`. -/
noncomputable def toRHSData
    {D : InitialThetaData AG TG}
    (G : GeneratedRHSData.{u, v, w} D) : RHSData.{u, v} D where
  container := G.container
  proc_standard := G.proc_standard
  toRational_finite := G.toRational_finite
  toRational_infinite := G.toRational_infinite
  vol := G.vol
  hull := G.hull
  thetaPilot := G.outputs.unionRegion
  thetaPilot_hullAdmissible := G.union_hullAdmissible
  thetaPilot_le_shell := G.outputs.unionRegion_le_logShell

end GeneratedRHSData

/-- Generated source data including one distinguished native q-output. -/
structure GeneratedNativeSource
    (D : InitialThetaData AG TG)
    (Q : QPilotData D) : Type (max (u + 1) (v + 1) (w + 1)) where
  rhs : GeneratedRHSData.{u, v, w} D
  native : rhs.outputs.Output
  nativeVolume :
    rhs.vol.processionVol (rhs.outputs.realize native) = Q.lhs
  processionVol_mono :
    ∀ {R S : ∀ i, rhs.container.AdmissibleRegion i},
      (∀ i, R i ≤ S i) →
        rhs.vol.processionVol R ≤ rhs.vol.processionVol S

namespace GeneratedNativeSource

/-- The public Corollary 3.12 bundle generated by the source data. -/
noncomputable def toVariantData
    {D : InitialThetaData AG TG} {Q : QPilotData D}
    (S : GeneratedNativeSource.{u, v, w} D Q) :
    Corollary312VariantData.{u, v} AG TG where
  data := D
  qPilot := Q
  rhsData := S.rhs.toRHSData

/-- The distinguished output produces an actual public-type witness. -/
noncomputable def toActualPilotWitness
    {D : InitialThetaData AG TG} {Q : QPilotData D}
    (S : GeneratedNativeSource.{u, v, w} D Q) :
    ActualPilotWitness S.toVariantData where
  region := S.rhs.outputs.realize S.native
  region_le_thetaPilot :=
    S.rhs.outputs.realize_le_unionRegion S.native
  qVolume := S.nativeVolume
  processionVol_mono := S.processionVol_mono

/-- Generated actual-output data close the public numerical variant. -/
theorem corollary312Variant
    {D : InitialThetaData AG TG} {Q : QPilotData D}
    (S : GeneratedNativeSource.{u, v, w} D Q) :
    Corollary312Variant S.toVariantData :=
  S.toActualPilotWitness.corollary312Variant

end GeneratedNativeSource
end IUTActualTypes
